using './breakpointapi-containerapp.module.bicep'

param appinsights_outputs_appinsightsconnectionstring = '{{ .Env.APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
param breakpointapi_containerimage = '{{ .Image }}'
param breakpointapi_containerport = '{{ targetPortOrDefault 8080 }}'
param breakpointapi_identity_outputs_clientid = '{{ .Env.BREAKPOINTAPI_IDENTITY_CLIENTID }}'
param breakpointapi_identity_outputs_id = '{{ .Env.BREAKPOINTAPI_IDENTITY_ID }}'
param breakpointenv_outputs_azure_container_apps_environment_default_domain = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param breakpointenv_outputs_azure_container_apps_environment_id = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param breakpointenv_outputs_azure_container_registry_endpoint = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param breakpointenv_outputs_azure_container_registry_managed_identity_id = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param keyvault_outputs_vaulturi = '{{ .Env.KEYVAULT_VAULTURI }}'
param postgres_password_value = '{{ securedParameter "postgres_password" }}'
param storage_outputs_blobendpoint = '{{ .Env.STORAGE_BLOBENDPOINT }}'
