using './breakpointanalyzerfunction-containerapp.module.bicep'

param appinsights_outputs_appinsightsconnectionstring = '{{ .Env.APPINSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
param breakpointanalyzerfunction_containerimage = '{{ .Image }}'
param breakpointanalyzerfunction_identity_outputs_clientid = '{{ .Env.BREAKPOINTANALYZERFUNCTION_IDENTITY_CLIENTID }}'
param breakpointanalyzerfunction_identity_outputs_id = '{{ .Env.BREAKPOINTANALYZERFUNCTION_IDENTITY_ID }}'
param breakpointenv_outputs_azure_container_apps_environment_default_domain = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}'
param breakpointenv_outputs_azure_container_apps_environment_id = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}'
param breakpointenv_outputs_azure_container_registry_endpoint = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_REGISTRY_ENDPOINT }}'
param breakpointenv_outputs_azure_container_registry_managed_identity_id = '{{ .Env.BREAKPOINTENV_AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}'
param keyvault_outputs_vaulturi = '{{ .Env.KEYVAULT_VAULTURI }}'
param postgres_password_value = '{{ securedParameter "postgres_password" }}'
param storage_outputs_blobendpoint = '{{ .Env.STORAGE_BLOBENDPOINT }}'
param storage_outputs_queueendpoint = '{{ .Env.STORAGE_QUEUEENDPOINT }}'
param storage_outputs_tableendpoint = '{{ .Env.STORAGE_TABLEENDPOINT }}'
